version: '3'
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
  scheduler:
    container_name: scheduler
    build: ./docker-files/python27
    working_dir: /usr/src
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: bash app/init_scheduler.sh data/data.encrypted redis
    volumes:
      - ./app:/usr/src/app
      - ./data:/usr/src/data
      - ./config:/usr/src/config
  processor:
    container_name: processor
    build: ./docker-files/python27
    working_dir: /usr/src
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: bash app/init_processor.sh data/aes.encrypted redis
    volumes:
      - ./app:/usr/src/app
      - ./data:/usr/src/data
      - ./config:/usr/src/config
  validator:
    container_name: validator
    build: ./docker-files/python27
    working_dir: /usr/src
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: python app/validator.py --redisHost redis
    volumes:
      - ./app:/usr/src/app
      - ./data:/usr/src/data
      - ./config:/usr/src/config
    depends_on:
      - redis
  dashboard:
    container_name: rq-dashboard
    build: ./docker-files/rq-dashboard
    ports:
      - 8080:9181
    environment:
      - RQ_DASHBOARD_REDIS_HOST=redis
    depends_on:
      - redis
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    depends_on:
      - redis
  schedulernode:
    container_name: schedulernode
    image: centos:7
    working_dir: /usr/src/docker-env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./docker-env:/usr/src/docker-env
      - ./docker-env/waagent:/var/lib/waagent
    command: bash scheduler_bootstrap.sh redis
  processornode:
    container_name: processornode
    image: centos:7
    working_dir: /usr/src/docker-env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./docker-env:/usr/src/docker-env
      - ./docker-env/waagent:/var/lib/waagent
    command: bash processor_bootstrap.sh redis




